spring:
  profiles:
    active: ${APP_ENV:dev}

  application:
    name: demo

  hazelcast:
    config: classpath:hazelcast.yaml

server:
  port: 9999
  servlet:
    encoding:
      charset: UTF-8

app:
  security:
    jwt:
      secret-key: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
      access:
        expiration: 86400000
      refresh:
        expiration: 604800000

backend-core:
  mask:
    enabled: true
    hidden-types:
      middle:
        fields: ic,nationalId,username,phone,mobileNumber,cardNumber,creditCardNumber

      tail:
        fields: email

  crypto:
    enabled: false
    rsa:
      algorithms: "${RSA_ALGORITHMS:RSA/ECB/PKCS1Padding}"
    aes:
      algorithms: "${AES_ALGORITHMS:AES/CBC/PKCS5Padding}"
