version: '3.8'

services:
  eyr-nginx:
    container_name: eyr-nginx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs/server.crt:/etc/nginx/ssl/server.crt
      - ./certs/server.key:/etc/nginx/ssl/server.key
      - ./certs/ca.crt:/etc/nginx/ssl/ca.crt
    ports:
      - "80:80"
      - "443:443"
    networks:
      - eyr

  eyr-backend-1:
    container_name: eyr-backend-1
    image: eyr-backend
    expose:
      - 8080
    networks:
      eyr:
        ipv4_address: 172.20.0.10

  eyr-backend-2:
    container_name: eyr-backend-2
    image: eyr-backend
    expose:
      - 8080
    networks:
      eyr:
        ipv4_address: 172.20.0.11

  # eyr-hazelcast:
  #   container_name: eyr-hazelcast
  #   image: hazelcast/hazelcast:5.5.0
  #   environment:
  #     - HZ_NETWORK_PUBLICADDRESS=eyr-hazelcast:5701
  #     - HZ_CLUSTERNAME=eyr-one-piece
  #   volumes:
  #     - ./hazelcast.yml:/opt/hazelcast/config/hazelcast.yml
  #   expose:
  #     - 5701
  #   ports:
  #     - '5701:5701'
  #   networks:
  #     - eyr

networks:
  eyr:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16