hazelcast:
  network:
    join:
      multicast:
        enabled: false
      tcp-ip:
        enabled: true
        members:
          - "eyr-hazelcast:5701"
  map:
    crypto:
      backup-count: 1
      async-backup-count: 1
      time-to-live-seconds: 10
